### PR TITLE
build-gcc: Address derps and miscellaneous changes

### PR DESCRIPTION
**Pull request by djchittoor**
- build-gcc: Address derp introduced in 2ce98c5.
- build-gcc: Increment parallel jobs by 2.
- editorconfig: Add EditorConfig configuration.
- editorconfig: Set shell script indentation to 2.
- treewide: Align scripts with EditorConfig settings.

### CODE REVIEW

**Comment by mvaisakh** [comment]
Looks good to me

**Comment by Forenche** [comment]
@djchittoor God

**Comment by flashokiller** [comment]
Super gwad

**Comment by flashokiller** [comment]
@flashokiller

**Comment by sohamxda7** [comment]
God ultra extreme

**Comment by Forenche** [comment]
@sohamxda7

**Pull request merged**
