### PR TITLE
workflows: strip the binaries before pushing

### PR DESCRIPTION
**Pull request by Jebaitedneko**
Signed-off-by: Jebaitedneko <Jebaitedneko@gmail.com>

### CODE REVIEW

**Comment by mvaisakh** [comment]
Looks good to me!

**Comment by Panchajanya1999** [comment]
Binaries are smoler now?

**Comment by mvaisakh** [comment]
Yes, ~90MB lesser according to him

**Comment by Forenche** [comment]
Why so much work for ~90mb ?

**Comment by Jebaitedneko** [comment]
cuz why not
those debug symbols won't be used anyways
AOSPA does the same for sdclang releases

**Comment by sourajitk** [comment]
SDclang deez

> cuz why not
> those debug symbols won't be used anyways
> AOSPA does the same for sdclang releases

**Comment by Forenche** [comment]
@Jebaitedneko Hmmz, makes sense

**Comment by Forenche** [comment]
> SDclang deez
> 
> > cuz why not
> > those debug symbols won't be used anyways
> > AOSPA does the same for sdclang releases

Nutzzzz

**Comment by Panchajanya1999** [comment]
> Yes, ~90MB lesser according to him

So eva is 50mb now?

**Comment by Divyanshu-Modi** [comment]
@Panchajanya1999 Damnnnnnnn!

**Comment by Forenche** [comment]
@Panchajanya1999 Faster clones now, gg

**Pull request merged**
